export function baseTrainings() {
  return [
    {
      id: 1,
      en: {
        title: 'Code of Conduct & Ethics',
    blurb: 'Mandatory principles for honesty, fairness, objectivity, and accountability.',
  desc: 'A practical, plain‑language guide to the behaviors expected of everyone in the organization. We explore real scenarios on gifts and hospitality, conflicts of interest, respectful conduct, and responsible use of company resources. You will learn how to seek advice, when and how to disclose concerns, and the protections available to you when speaking up. By the end, teams share a common language for ethics and clear steps for doing the right thing under pressure.',
        duration: '60–75 min',
        overview:
          'Establishes organization‑wide ethical standards, duties to clients and the public, and expectations for responsible conduct.',
        objectives: [
          'Define core ethical principles and duties',
          'Recognize conflicts and apply disclosure/recusal',
          'Handle gifts, hospitality, and inducements appropriately',
          'Report concerns via protected channels',
        ],
        modules: [
          'Principles & duties',
          'Acceptable behavior and professionalism',
          'Gifts & hospitality',
          'Conflicts of interest',
          'Speaking up & protection',
        ],
        audience: ['All staff', 'People managers', 'Compliance officers'],
        curriculum: [
          'Foundations and core principles',
          'Professionalism and acceptable conduct',
          'Gifts, hospitality, and inducements',
          'Identifying and managing conflicts',
          'Speaking up and protections',
        ],
        includes: ['Short videos', 'Downloadable policy checklist', 'Quiz and certificate'],
        video_url: 'https://www.youtube.com/watch?v=bU2w3gmM9n8',
        assessment: ['10‑question quiz', 'Scenario reflections'],
      },
      am: {
        title: 'የሥነ ምግባር ደንብ እና ሥነ-ምግባር',
  blurb: 'ለታማኝነት፣ ለፍትሃዊነት፣ ለገለልተኝነት እና ለተጠያቂነት لازم የሆኑ መርሆዎች።',
  desc: 'በቀላሉ የሚገባ መንገድ የድርጅቱ ሁሉ ሰው ከመጠበቁ ባህሪያት ጋር ያያያዙ መመሪያዎችን ያብራራል። ስጦታ እና መስተንግዶ፣ የጥቅም ግጭት፣ ክብር ያለው ባህሪ እና የድርጅት ሀብት ተጠቃሚ አጠቃቀም ላይ በእውነተኛ ምሳሌዎች ይማራሉ። ምክር መፈለግ መቼ እንደሚገባ፣ ስጋቶችን መመለስ እና በድርጅት ውስጥ በደህና መናገር ሲያደርጉ የሚገኙ ጥበቃዎች ይታወቃሉ። በመጨረሻ ቡድኖች አንድ የሥነ‑ምግባር ቋንቋ እና በግፊት ጊዜ ምን መደረግ እንደሚገባ ግልጽ ደረጃ ይኖራቸዋል።',
        duration: '60–75 ደቂቃ',
        overview:
          'በድርጅት አቀፍ ደረጃ የሥነ-ምግባር ደረጃዎችን፣ ለደንበኞች እና ለህዝብ ያሉ ግዴታዎችን እና ኃላፊነት የተሞላበት ምግባርን በተመለከተ የሚጠበቁ ነገሮችን ያወጣል።',
        objectives: [
          'ዋና ዋና የሥነ-ምግባር መርሆዎችን እና ግዴታዎችን መግለፅ',
          'ግጭቶችን መለየት እና ይፋ ማድረግን/ከኃላፊነት መነሳትን መተግበር',
          'ስጦታዎችን፣ መስተንግዶዎችን እና ማበረታቻዎችን በአግባቡ መያዝ',
          'ስጋቶችን በተጠበቁ ቻናሎች ሪፖርት ማድረግ',
        ],
        modules: [
          'መርሆዎች እና ግዴታዎች',
          'ተቀባይነት ያለው ባህሪ እና ሙያዊነት',
          'ስጦታዎች እና መስተንግዶ',
          'የጥቅም ግጭቶች',
          'ሀሳብን መግለፅ እና ጥበቃ',
        ],
        audience: ['ሁሉም ሰራተኞች', 'የሰው ኃይል አስተዳዳሪዎች', 'የሕግ ተገዢነት ኦፊሰሮች'],
        curriculum: [
          'መሠረታዊ መርሆዎች',
          'ሙያዊነት እና ተቀባይነት ያለው ባህሪ',
          'ስጦታ፣ መስተንግዶ እና ማበረታቻ',
          'ግጭቶችን መለየት እና መቆጣጠር',
          'ሀሳብ መግለፅ እና ጥበቃ',
        ],
        includes: ['አጭር ቪዲዮዎች', 'የፖሊሲ ቼክሊስት ማውረድ', 'ፈተና እና ምስክር ወረቀት'],
        video_url: 'https://www.youtube.com/watch?v=bU2w3gmM9n8',
        assessment: ['10 ጥያቄዎች ያሉት ፈተና', 'የሁኔታ ነጸብራቆች'],
      },
    },
    {
      id: 2,
      en: {
        title: 'Competency Framework',
    blurb: 'Role‑based standards, continuing professional education, and evidence.',
  desc: 'Build clear role profiles and level expectations so people know what “good” looks like today and tomorrow. We connect competencies to learning plans, set targets for continuing professional education, and show how to keep evidence that stands up to audit. Templates and examples help teams map gaps, track progress, and report confidently to leadership and regulators.',
        duration: '60–75 min',
        overview:
          'Sets out role profiles, competency standards, and record‑keeping so licensed functions remain fit and proper.',
        objectives: ['Map roles to standards', 'Plan CPE', 'Maintain training records'],
        modules: ['Role profiles', 'Standards & checks', 'CPE planning', 'Record‑keeping'],
  audience: ['HR', 'Compliance', 'Line managers'],
  curriculum: ['Role profiles', 'Competency mapping', 'CPE planning', 'Record‑keeping & evidence'],
  includes: ['Templates', 'Sample role grid', 'Quiz and certificate'],
  video_url: 'https://youtu.be/5lHj5mA3QF8?si=oQy1n3fX7X4xVU--',
        assessment: ['Checklist exercise', 'Short quiz'],
      },
      am: {
        title: 'የብቃት ማዕቀፍ',
    blurb: 'በሚና ላይ የተመሰረቱ መስፈርቶች፣ ቀጣይነት ያለው የሙያ ትምህርት እና ማስረጃ።',
  desc: 'ግልጽ የሚና መገለጫዎችን እና የደረጃ መጠን መጠበቂያዎችን በመመስረት ሰዎች ዛሬ እና ነገ ምን እንደ “ጥሩ” እንደሚባል ይወቁ። መርሃ ግብር ከብቃት ጋር በማዛመድ የቀጣይ የሙያ ትምህርት እቅዶችን እና ለምርመራ የሚቆሙ ማስረጃዎችን እንቆጥባለን። ቴምፕሌቶች እና ምሳሌዎች ክፍተቶችን ለመለየት፣ ለሂደት መከታተል እና ለመሪዎች እና ለባለስልጣኖች በእርግጥ ሪፖርት ለማድረግ ይረዳሉ።',
        duration: '60–75 ደቂቃ',
        overview:
          'ፈቃድ ያላቸው ተግባራት ብቁ እና ትክክለኛ ሆነው እንዲቀጥሉ የሚና መገለጫዎችን፣ የብቃት ደረጃዎችን እና የመዝገብ አያያዝን ያስቀምጣል።',
        objectives: ['ሚናዎችን ከመመዘኛዎች ጋር ማዛመድ', 'ቀጣይነት ያለው የሙያ ትምህርት ማቀድ', 'የሥልጠና መዝገቦችን መያዝ'],
        modules: ['የሚና መገለጫዎች', 'መስፈርቶች እና ማረጋገጫዎች', 'የቀጣይ የሙያ ትምህርት እቅድ', 'የመዝገብ አያያዝ'],
  audience: ['የሰው ሀብት', 'የህግ ተገዢነት', 'የመስመር አስተዳዳሪዎች'],
  curriculum: ['የሚና መገለጫዎች', 'የብቃት መዋቅሮች', 'የቀጣይ ሙያ ትምህርት እቅድ', 'መዝገብ አያያዝ እና ማስረጃ'],
  includes: ['ቴምፕሌቶች', 'የሚና ግሪድ ምሳሌ', 'ፈተና እና ምስክር ወረቀት'],
  video_url: 'https://youtu.be/5lHj5mA3QF8?si=oQy1n3fX7X4xVU--',
        assessment: ['የማረጋገጫ ዝርዝር ልምምድ', 'አጭር ፈተና'],
      },
    },
    {
      id: 3,
      en: {
        title: 'Risk Management & Compliance',
    blurb: 'Identify, assess, and mitigate operational, regulatory, cyber, and reputational risks.',
  desc: 'Learn a clear end‑to‑end approach to identifying risks, scoring them consistently, and assigning ownership. We practice building a live risk register, designing proportionate controls, and setting up monitoring and reporting that decision‑makers can trust. Case studies bring operational, regulatory, cyber, and reputational risks to life so teams can apply the methods immediately.',
        duration: '75–90 min',
        overview:
          'Introduces an integrated risk framework with clear ownership, controls, and monitoring aligned to compliance obligations.',
        objectives: ['Build a risk register', 'Design controls', 'Monitor & report'],
        modules: ['Risk taxonomy', 'Assessment & scoring', 'Controls', 'Monitoring & reporting'],
  audience: ['Risk & Compliance teams', 'Process owners'],
  curriculum: ['Risk taxonomy', 'Scoring & heatmaps', 'Control design', 'Monitoring & reporting'],
  includes: ['Risk register template', 'Case study workbook', 'Quiz and certificate'],
  video_url: 'https://youtu.be/BLAEuVSAlVM?si=FaaLL6Mi0R5_EXAL',
        assessment: ['Case study', 'Quiz'],
      },
      am: {
        title: 'የስጋት አስተዳደር እና የህግ ተገዢነት',
    blurb: 'የአሰራር፣ የቁጥጥር፣ የሳይበር እና የስም ስጋቶችን መለየት፣ መገምገም እና መቀነስ።',
  desc: 'ስጋቶችን መለየት፣ መደምደም እና ባለቤትነት መመደብ የሚያሳይ ግልጽ መንገድ ትማራላችሁ። በተግባር የስጋት መዝገብ እንገነባለን፣ ተመጣጣኝ ቁጥጥሮችን እንንድፍ እና ለመሪዎች ተመን የሚሰጥ ክትትል እና ሪፖርት እንዘጋጅ። የጉዳይ ጥናቶች የአሰራር፣ የሕግ ተገዢነት፣ የሳይበር እና የስም ስጋቶችን በእውነት ያቀርባሉ እና ዘዴዎቹን በፈጣን እንዲተግብሩ ያግዛችኋል።',
        duration: '75–90 ደቂቃ',
        overview:
          'ከህግ ተገዢነት ግዴታዎች ጋር የተጣጣመ ግልጽ ባለቤትነት፣ ቁጥጥሮች እና ክትትል ያለው የተቀናጀ የስጋት ማዕቀፍ ያስተዋውቃል።',
        objectives: ['የስጋት መዝገብ መገንባት', 'የቁጥጥር ዘዴዎችን መንደፍ', 'መከታተል እና ሪፖርት ማድረግ'],
        modules: ['የስጋት ምደባ', 'ግምገማ እና የውጤት አሰጣጥ', 'ቁጥጥሮች', 'ክትትል እና ሪፖርት ማድረግ'],
  audience: ['የስጋት እና የህግ ተገዢነት ቡድኖች', 'የሂደት ባለቤቶች'],
  curriculum: ['የስጋት ምደባ', 'ውጤት እና ሙቀት ካርታ', 'የቁጥጥር ንድፍ', 'ክትትል እና ሪፖርት ማድረግ'],
  includes: ['የስጋት መዝገብ ቴምፕሌት', 'የጉዳይ ጥናት ወረቀት', 'ፈተና እና ምስክር ወረቀት'],
  video_url: 'https://youtu.be/BLAEuVSAlVM?si=FaaLL6Mi0R5_EXAL',
        assessment: ['የጉዳይ ጥናት', 'ፈተና'],
      },
    },
    {
      id: 4,
      en: {
        title: 'Whistleblowing & Reporting',
    blurb: 'Confidential channels, anti‑retaliation protections, and investigation workflows.',
  desc: 'Create a speak‑up culture with safe, simple reporting paths for employees and third parties. We cover anonymous and named options, intake and triage, documentation standards, and how to investigate fairly while protecting confidentiality. You will leave with clear guidance on anti‑retaliation, manager responsibilities, and closing the loop with reporters.',
        duration: '45–60 min',
        overview:
          'Explains safe reporting, case handling lifecycles, confidentiality, and protections against retaliation.',
        objectives: ['Use channels safely', 'Triage & investigate', 'Protect reporters'],
        modules: ['Speaking up', 'Intake & triage', 'Investigation', 'Closure & feedback'],
  audience: ['All staff', 'HR', 'Compliance'],
  curriculum: ['Speaking up channels', 'Intake & triage', 'Investigation basics', 'Closure & feedback'],
  includes: ['Policy poster', 'Reporting flowchart', 'Short quiz'],
  video_url: 'https://youtu.be/51k3UASQE5E?si=U7KphQdqtgGSOtWK',
        assessment: ['Scenario practice', 'Short quiz'],
      },
      am: {
        title: 'ጥቆማ እና ሪፖርት ማድረግ',
    blurb: 'ሚስጥራዊ ቻናሎች፣ ከበቀል ድርጊት ጥበቃ እና የምርመራ የስራ  ሂደቶች።',
  desc: 'ከሰራተኞች እና ከውጭ ወገኖች ጋር የሚሰራ የበለጠ ቀላል እና ደህና የሆነ የሪፖርት መንገድ እንቋቋማለን። አናኒማስ ወይም በስም ሪፖርት፣ መቀበል እና መለየት፣ ሰነድ መዝግብ መስፈርቶች እና ሚስጥራዊነትን በመጠበቅ ፍትሃዊ ምርመራ መካሄድ እንከፍላለን። ከበቀል ድርጊት ከመከላከል ጀምሮ የሥራ አስፈፃሚዎች ኃላፊነቶች እስከ ከሪፖርተሮች ጋር መመለስ ድረስ ግልጽ መመሪያ ይወስዳሉ።',
        duration: '45–60 ደቂቃ',
        overview:
          'ደህንነቱ የተጠበቀ ሪፖርት ማድረግን፣ የጉዳይ አያያዝ የህይወት ኡደቶችን፣ ሚስጥራዊነትን እና ከበቀል ድርጊት ጥበቃዎችን ያብራራል።',
        objectives: ['ቻናሎችን ደህንነቱ በተጠበቀ ሁኔታ መጠቀም', 'ጉዳዮችን መለየት እና መመርመር', 'ሪፖርተሮችን መጠበቅ'],
        modules: ['ሀሳብን መግለፅ', 'መቀበል እና መለየት', 'ምርመራ', 'መዝጊያ እና ግብረመልስ'],
  audience: ['ሁሉም ሰራተኞች', 'የሰው ሀብት', 'የህግ ተገዢነት'],
  curriculum: ['የሀሳብ መግለፅ ቻናሎች', 'መቀበል እና መለየት', 'የምርመራ መሠረቶች', 'መዝጊያ እና ግብረመልስ'],
  includes: ['የፖሊሲ ፖስተር', 'የሪፖርት ሂደት ካርታ', 'አጭር ፈተና'],
  video_url: 'https://youtu.be/51k3UASQE5E?si=U7KphQdqtgGSOtWK',
        assessment: ['የሁኔታ ልምምድ', 'አጭር ፈተና'],
      },
    },
    {
      id: 5,
      en: {
        title: 'Conflict of Interest Management',
    blurb: 'Disclosure, recusal, and monitoring to manage conflicts.',
  desc: 'Recognize common conflict patterns early—personal, financial, and organizational—and respond with proportionate controls. We walk through simple disclosure flows, when to recuse, how to maintain registers, and how to monitor attestations over time. Practical examples help teams talk about conflicts confidently and protect decisions from bias.',
        duration: '45–60 min',
        overview:
          'Shows how to identify personal, financial, and organizational conflicts and apply controls across the lifecycle.',
        objectives: ['Spot conflicts', 'Disclose/recuse', 'Monitor & attest'],
        modules: ['Conflict types', 'Processes & registers', 'Controls', 'Monitoring'],
  audience: ['All staff', 'Managers'],
  curriculum: ['Conflict types and examples', 'Process & registers', 'Controls toolkit', 'Monitoring & attestations'],
  includes: ['Register template', 'Scenario workbook', 'Quiz'],
  video_url: 'https://youtu.be/6x99iz_W8TU?si=imkcHo6rCo9bHj4y',
        assessment: ['Register exercise', 'Quiz'],
      },
      am: {
        title: 'የጥቅም ግጭት አስተዳደር',
    blurb: 'ግጭቶችን ለማስተዳደር ይፋ ማድረግ፣ ከኃላፊነት መነሳት እና ክትትል።',
  desc: 'የተለመዱ የግጭት ቅጦችን—የግል፣ የገንዘብ እና የድርጅት—በፍጥነት መለየት እና ተመጣጣኝ ቁጥጥሮችን መተግበር ትማራሉ። ቀላል የይፋ ሂደቶችን እና መቼ ከኃላፊነት መነሳት እንደሚገባ እንመራለን፣ መዝገቦች እንዴት መያዝ እና ማረጋገጫዎችን በጊዜ ሂደት እንዴት መከታተል እንደሚቻል እናሳያለን። ተግባራዊ ምሳሌዎች ውሳኔዎች ከአፈና እንዲታደጉ ይረዳሉ።',
        duration: '45–60 ደቂቃ',
        overview:
          'የግል፣ የገንዘብ እና የድርጅት ግጭቶችን እንዴት መለየት እና በህይወት ኡደት ውስጥ ቁጥጥሮችን መተግበር እንደሚቻል ያሳያል።',
        objectives: ['ግጭቶችን መለየት', 'ይፋ ማድረግ/ከኃላፊነት መነሳት', 'መከታተል እና ማረጋገጥ'],
        modules: ['የግጭት ዓይነቶች', 'ሂደቶች እና መዝገቦች', 'ቁጥጥሮች', 'ክትትል'],
  audience: ['ሁሉም ሰራተኞች', 'አስተዳሪዎች'],
  curriculum: ['የግጭት ዓይነቶች እና ምሳሌዎች', 'ሂደት እና መዝገቦች', 'የቁጥጥር መሳሪያዎች', 'ክትትል እና ማረጋገጥ'],
  includes: ['የመዝገብ ቴምፕሌት', 'የሁኔታ እትም', 'ፈተና'],
  video_url: 'https://youtu.be/6x99iz_W8TU?si=imkcHo6rCo9bHj4y',
        assessment: ['የመዝገብ ልምምድ', 'ፈተና'],
      },
    },
    {
      id: 6,
      en: {
        title: 'Cybersecurity & Data Protection',
    blurb: 'Threat awareness, incident reporting, access control, and data handling.',
  desc: 'Strengthen cyber hygiene and build everyday security habits that actually stick. We cover phishing and social engineering, strong passwords and MFA, device and account hygiene, and practical data handling aligned to privacy obligations. You will also learn how to classify and share data safely, report incidents quickly, and support a prompt response.',
        duration: '60–75 min',
        overview:
          'Covers cyber hygiene, phishing awareness, secure access, and data protection aligned to privacy obligations.',
        objectives: ['Spot phishing', 'Report incidents', 'Protect data'],
        modules: ['Threats', 'Accounts & access', 'Data handling', 'Incident response'],
  audience: ['All staff', 'IT'],
  curriculum: ['Threat landscape', 'Accounts & access', 'Data handling', 'Incident response basics'],
  includes: ['Phishing drill', 'Quick reference guide', 'Quiz and certificate'],
  video_url: 'https://youtu.be/UpkqXK0B2E0?si=MRFaUM8wgxudE0YH',
        assessment: ['Phishing drill', 'Quiz'],
      },
      am: {
        title: 'የሳይበር ደህንነት እና የመረጃ ጥበቃ',
    blurb: 'የስጋት ግንዛቤ፣ የአደጋ ሪፖርት አቀራረብ፣ የመዳረሻ ቁጥጥር እና የመረጃ አያያዝ።',
  desc: 'የሳይበር ንፅህናን እና በየቀኑ የሚጠቅሙ የደህንነት ልምዶችን እንጠናከራለን። የማስገር እና ሶሻል ኢንጂነሪንግ፣ ጠንካራ የይለፍ ቃል እና MFA፣ የመሣሪያ እና መለያ ንፅህና እና ከግላዊነት ግዴታዎች ጋር የተጣጣመ ተግባራዊ የመረጃ አያያዝ እንሸፍናለን። መረጃን መመደብና በደህና መካፈል፣ ክስተቶችን በፍጥነት ሪፖርት ማድረግ እና ፈጣን ምላሽን መደገፍ ይማራሉ።',
        duration: '60–75 ደቂቃ',
        overview:
          'የሳይበር ንፅህናን፣ የማስገር ግንዛቤን፣ ደህንነቱ የተጠበቀ መዳረሻን እና ከግላዊነት ግዴታዎች ጋር የተጣጣመ የመረጃ ጥበቃን ይሸፍናል።',
        objectives: ['የማስገር ሙከራዎችን መለየት', 'ክስተቶችን ሪፖርት ማድረግ', 'መረጃን መጠበቅ'],
        modules: ['ስጋቶች', 'መለያዎች እና መዳረሻ', 'የመረጃ አያያዝ', 'የአደጋ ምላሽ'],
  audience: ['ሁሉም ሰራተኞች', 'የመረጃ ቴክኖሎጂ'],
  curriculum: ['የስጋት አካባቢ', 'መለያዎች እና መዳረሻ', 'የመረጃ አያያዝ', 'የአደጋ ምላሽ መሠረቶች'],
  includes: ['የማስገር ልምምድ', 'ፈጣን መመሪያ', 'ፈተና እና ምስክር ወረቀት'],
  video_url: 'https://youtu.be/UpkqXK0B2E0?si=MRFaUM8wgxudE0YH',
        assessment: ['የማስገር ልምምድ', 'ፈተና'],
      },
    },
    {
      id: 7,
      en: {
        title: 'AML & CFT',
    blurb: 'KYC/CDD, risk‑based monitoring, and STR workflows.',
  desc: 'Understand AML/CFT pillars and build a risk‑based customer lifecycle from onboarding to ongoing monitoring. We practice KYC/CDD and when to escalate to EDD, tune scenarios and red flags, and prepare STR/SAR that meets regulatory expectations. Real examples help teams balance friction with effectiveness while protecting the institution and its customers.',
        duration: '75–90 min',
        overview:
          'Walks through AML/CFT pillars, risk‑based customer due diligence, ongoing monitoring, and suspicious reporting.',
        objectives: ['Risk rating', 'CDD & EDD', 'Detect & report'],
        modules: ['Legal framework', 'KYC/CDD', 'Monitoring', 'STR/SAR'],
  audience: ['Front office', 'Operations', 'Compliance'],
  curriculum: ['Legal framework', 'KYC & CDD', 'Ongoing monitoring', 'STR/SAR process'],
  includes: ['CDD checklist', 'Red flags guide', 'Quiz and certificate'],
  video_url: 'https://youtu.be/kG_Vxk7WkSg?si=mvAHqRzq_HgdEqs7',
        assessment: ['Case review', 'Quiz'],
      },
      am: {
        title: 'የገንዘብ ህገ-ወጥ ዝውውርን እና የሽብርተኝነት ፋይናንስን መከላከል (AML & CFT)',
    blurb: 'የደንበኞችን ማንነት ማወቅ/የደንበኛ ተገቢውን ጥንቃቄ (KYC/CDD)፣ በአደጋ ላይ የተመሰረተ ክትትል እና አጠራጣሪ የግብይት ሪፖርት (STR) የስራ  ሂደቶች።',
  desc: 'የ AML/CFT ምሰሶዎችን በግልጽ እና ተግባራዊ መንገድ እንመለከታለን። ከመጀመሪያ መመዝገብ እስከ ቀጣይ ክትትል ድረስ በአደጋ ላይ የተመሰረተ የደንበኛ ሕይወት ዑደት እንገነባለን፣ KYC/CDD እና ወደ EDD መሻሻል መቼ እንደሚገባ እናሳያለን። ሁኔታዎችን እና ቀይ ምልክቶችን እንማራለን እና ከህጋዊ ተስፋፋት ጋር የሚጣጣሙ STR/SAR እንዘጋጃለን።',
        duration: '75–90 ደቂቃ',
        overview:
          'የ AML/CFT ምሰሶዎችን፣ በአደጋ ላይ የተመሰረተ የደንበኛ ተገቢውን ጥንቃቄ፣ ቀጣይነት ያለው ክትትል እና አጠራጣሪ ሪፖርት ማድረግን ይመራል።',
        objectives: ['የስጋት ደረጃ አሰጣጥ', 'የደንበኛ ተገቢውን ጥንቃቄ እና የተሻሻለ ተገቢውን ጥንቃቄ (CDD & EDD)', 'መለየት እና ሪፖርት ማድረግ'],
        modules: ['ህጋዊ ማዕቀፍ', 'የደንበኞችን ማንነት ማወቅ/የደንበኛ ተገቢውን ጥንቃቄ (KYC/CDD)', 'ክትትል', 'አጠራጣሪ የግብይት ሪፖርት/አጠራጣሪ እንቅስቃሴ ሪፖርት (STR/SAR)'],
  audience: ['የፊት መስመር ሰራተኞች', 'ኦፕሬሽኖች', 'የህግ ተገዢነት'],
  curriculum: ['ህጋዊ ማዕቀፍ', 'KYC & CDD', 'ቀጣይ ክትትል', 'STR/SAR ሂደት'],
  includes: ['የCDD ቼክሊስት', 'የቀይ ምልክቶች መመሪያ', 'ፈተና እና ምስክር ወረቀት'],
  video_url: 'https://youtu.be/kG_Vxk7WkSg?si=mvAHqRzq_HgdEqs7',
        assessment: ['የጉዳይ ግምገማ', 'ፈተና'],
      },
    },
    {
      id: 8,
      en: {
        title: 'Insider Trading & Market Manipulation',
    blurb: 'MNPI handling, market abuse patterns, and prevention.',
  desc: 'Protect material non‑public information (MNPI) and avoid prohibited conduct with clear, practical controls. We cover information barriers and wall‑crossing, pre‑clearance and personal account dealing, and common market abuse patterns. You will learn when to escalate, how surveillance works at a high level, and the consequences of breaches for individuals and firms.',
        duration: '60–75 min',
        overview:
          'Explains insider information controls, prohibited conduct, trade surveillance basics, and enforcement consequences.',
        objectives: ['Handle MNPI', 'Spot abuse', 'Prevent & escalate'],
        modules: ['Definitions', "Do's & don'ts", 'Surveillance', 'Enforcement'],
  audience: ['Capital markets roles', 'Executives'],
  curriculum: ['Definitions & scope', "Do's & don'ts", 'Surveillance basics', 'Enforcement & penalties'],
  includes: ['Insider list template', 'Case examples', 'Quiz and certificate'],
  video_url: 'https://youtu.be/hrT2-ixBjwY?si=TToNcGoVmsW6Bgeb',
        assessment: ['Scenario analysis', 'Quiz'],
      },
      am: {
        title: 'የውስጥ አዋቂ ንግድ እና የገበያ ማጭበርበር',
    blurb: 'ቁሳዊ ያልሆነ የህዝብ መረጃ (MNPI) አያያዝ፣ የገበያ አላግባብ መጠቀም ዘይቤዎች እና መከላከል።',
  desc: 'ቁሳዊ ያልሆነ የህዝብ መረጃን (MNPI) በመጠበቅ እና የተከለከሉ ድርጊቶችን በመቀነስ በተግባር የሚሰሩ ቁጥጥሮችን እንቀርባለን። የመረጃ መከለከያዎች እና ዋል‑ክሮሲንግ፣ ቀድሞ ፍቃድ እና የግል መለያ ንግድ እና የገበያ አላግባብ ዘይቤዎች ይካተታሉ። መቼ ማሳወቅ እንደሚገባ፣ ክትትል እንዴት እንደሚሰራ እና ለግለሰቦች እና ለድርጅቶች የሚከተሉ ውጤቶች ይታወቃሉ።',
        duration: '60–75 ደቂቃ',
        overview:
          'የውስጥ አዋቂ የመረጃ ቁጥጥሮችን፣ የተከለከሉ ድርጊቶችን፣ የንግድ ክትትል መሰረታዊ ነገሮችን እና የማስፈጸሚያ ውጤቶችን ያብራራል።',
        objectives: ['ቁሳዊ ያልሆነ የህዝብ መረጃን መያዝ', 'አላግባብ መጠቀምን መለየት', 'መከላከል እና ማሳወቅ'],
        modules: ['ትርጓሜዎች', 'የሚደረጉ እና የማይደረጉ ነገሮች', 'ክትትል', 'ማስፈጸም'],
  audience: ['የካፒታል ገበያ ሚናዎች', 'ሥራ አስፈፃሚዎች'],
  curriculum: ['ትርጓሜ እና ክልል', 'የሚደረጉ እና የማይደረጉ ነገሮች', 'መመርመሪያ መሠረቶች', 'ማስፈፀሚያ እና ቅጣቶች'],
  includes: ['የውስጥ ዝርዝር ቴምፕሌት', 'የጉዳይ ምሳሌዎች', 'ፈተና እና ምስክር ወረቀት'],
  video_url: 'https://youtu.be/hrT2-ixBjwY?si=TToNcGoVmsW6Bgeb',
        assessment: ['የሁኔታ ትንተና', 'ፈተና'],
      },
    },
  ];
}
